---
# tasks file for hw201
- name: Ping my servers
  ping:

- name: Install git, docker, python3
  package:
    name: "{{item}}"
    state: present
  loop:
  - git
  - docker
  - python3  

- name: Create user
  user:
    name: hw20
    password: test123
    state: present
    group: sudo 
    shell: /bin/sh
    system: no
    createhome: yes
    home: /opt/hw20

- name: Clone a public git repository
  become: true
  become_user: hw20
  git:
    repo: 'https://github.com/octocat/Hello-World.git'
    dest: /opt/hw20/hello-world
