Vagrant.configure("2") do |config|
  config.vm.define :vm_1 do |vm_1|
    vm_1.vm.box = "ubuntu/trusty64"
    vm_1.vm.network :private_network, ip: "127.0.0.2"
    vm_1.vm.hostname = "vm1"
  end

  config.vm.define :vm_2 do |vm_2|
    vm_2.vm.box = "ubuntu/trusty64"
    vm_2.vm.network :private_network, ip: "127.0.0.3"
    vm_2.vm.hostname = "vm2"
  end
end