---
- name: install default Apache Web servers
  hosts: Group_2
  become: yes

  tasks:
  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Install Apache WebSever
    apt: name=apache2 state=latest

  - name: Start Apache
    service: name=apache2 state=started